### ISSUE TITLE
crash app on android

### ISSUE THREAD

**Issue by widget-404** [Teknasyon-Teknoloji/desk360-flutter-sdk#2]
Desk360flutter.start() crash my android app after the loading screen.

here is relevant console result
E/FLUTTER (22948): io.flutter.plugin.common.MethodCall@e030a72
E/FLUTTER (22948): io.flutter.plugin.common.MethodCall@1735bbe
D/OkHttp  (22948): --> POST https://teknasyon.desk360.com/api/v1/sdk/configurations
D/OkHttp  (22948): Content-Type: application/json; charset=UTF-8
D/OkHttp  (22948): Content-Length: 42
D/OkHttp  (22948): Authorization: Bearer HoV8gyw2KIGtTcrSqX0S7xjyHcUEN3uJhboYLUHwxcVZzVP9tCohHkMg3iyIMj7Q8vxQOJjMMIaT6owR
D/OkHttp  (22948): {"country_code":"PK","language_code":"en"}
D/OkHttp  (22948): --> END POST (42-byte body)
D/ColorViewRootUtil(22948): initSwipState, isDisplayCompatApp false
D/ColorViewRootUtil(22948): mScreenHeight 1600, mScreenWidth 720
D/WindowManager(22948): Add to mViews: DecorView@7239c3a[Desk360SplashActivity], this = android.view.WindowManagerGlobal@876ab23,pkg= com.gomeat.app
I/Choreographer(22948): Skipped 1 frames!  The application may be doing too much work on its main thread.
I/Choreographer(22948): Skipped 12 frames!  The application may be doing too much work on its main thread.
D/ColorViewRootUtil(22948): initSwipState, isDisplayCompatApp false
D/ColorViewRootUtil(22948): mScreenHeight 1600, mScreenWidth 720
D/SurfaceView(22948): 127400373 updateRequestedVisibility, mViewVisibility:true, mWindowVisibility:false, mWindowStopped:false by android.view.SurfaceView.onWindowVisibilityChanged:301 android.view.View.dispatchWindowVisibilityChanged:14512 android.view.ViewGroup.dispatchWindowVisibilityChanged:1590 android.view.ViewGroup.dispatchWindowVisibilityChanged:1590 android.view.ViewGroup.dispatchWindowVisibilityChanged:1590 android.view.ViewGroup.dispatchWindowVisibilityChanged:1590 android.view.ViewRootImpl.performTraversals:2366 android.view.ViewRootImpl.doTraversal:2034 
I/SurfaceView(22948): 127400373 Changes: creating=false format=false size=false visible=true alpha=false mUseAlpha=false visible=true left=false top=false
I/SurfaceView(22948): 127400373 Cur surface: Surface(name=null)/@0x2405d6f, visible=false
I/SurfaceView(22948): 127400373 visibleChanged:true -> SurfaceHolder.Callback.surfaceDestroyed
I/PswFrameworkFactoryImpl(22948): get feature:IPswScreenModeFeature
V/SurfaceView(22948): Layout: x=0 y=0 w=720 h=1600, frame=Rect(0, 0 - 720, 1600)
D/SurfaceView(22948): 105265327 windowPositionLost, frameNr = 0
I/SurfaceView(22948): 127400373  updateSurface this = io.flutter.embedding.android.FlutterSurfaceView{797f9b5 V.E...... ........ 0,0-720,1600}  surface.isValid = false
D/SurfaceView(22948): 127400373 updateSurface: no valid surface
D/SurfaceView(22948): 127400373 updateRequestedVisibility, mViewVisibility:true, mWindowVisibility:false, mWindowStopped:true by android.view.SurfaceView.windowStopped:266 android.view.ViewRootImpl.setWindowStopped:1763 android.view.WindowManagerGlobal.setStoppedState:687 android.app.Activity.performStop:8209 android.app.ActivityThread.callActivityOnStop:4939 android.app.ActivityThread.performStopActivityInner:4917 android.app.ActivityThread.handleStopActivity:4999 android.app.servertransaction.StopActivityItem.execute:41 
I/SurfaceView(22948): 127400373  updateSurface this = io.flutter.embedding.android.FlutterSurfaceView{797f9b5 V.E...... ........ 0,0-720,1600}  surface.isValid = false
D/SurfaceView(22948): 127400373 updateSurface: no valid surface
I/SurfaceView(22948): 127400373  updateSurface this = io.flutter.embedding.android.FlutterSurfaceView{797f9b5 V.E...... ........ 0,0-720,1600}  surface.isValid = false
D/SurfaceView(22948): 127400373 updateSurface: no valid surface
D/OkHttp  (22948): <-- 200 OK https://teknasyon.desk360.com/login (1151ms)
D/OkHttp  (22948): Date: Thu, 20 Oct 2022 20:01:48 GMT
D/OkHttp  (22948): Content-Type: text/html; charset=UTF-8
D/OkHttp  (22948): Transfer-Encoding: chunked
D/OkHttp  (22948): Connection: keep-alive
D/OkHttp  (22948): Server: nginx/1.20.0
D/OkHttp  (22948): Cache-Control: no-cache, private
D/OkHttp  (22948): X-Frame-Options: SAMEORIGIN
D/OkHttp  (22948): Set-Cookie: XSRF-TOKEN=eyJpdiI6ImhUODI3WGVmQWdDZ1hEd3Q0YkNmQ1E9PSIsInZhbHVlIjoibEpBZU0yWFBZbHdZMGlNM3loYzJ2aDlOUWFnYUJlQ1ZCVzlLS2J5XC9DNndnWnBDbm4wSk11TzZ5Vkl5bm1qeDQiLCJtYWMiOiJhMmY2YTEyMzQyYWE1YTM1MWQ4NGVmOTYxOWZiYjYwMDM0OTNkMGNhMDgzYTRhY2UxMWUxNTkxYTY5Yjg5ZDNjIn0%3D; expires=Sat, 19-Nov-2022 20:01:48 GMT; Max-Age=2592000; path=/; secure
D/OkHttp  (22948): Set-Cookie: desk360_session=eyJpdiI6InJTYjQrV2RNOGdhTVNEekpwRFBzOUE9PSIsInZhbHVlIjoidmNydXhwYXRnOXAxUFBaK0pJQzFpU3hwSTN1eWI0ZlZCQ21xc0NiXC9DNkNQa0x2YmRwVFFaYVpYTHVcL284RUJ0IiwibWFjIjoiOGI3YWRjMDRiMDQ0ODg2MDFkYzdkM2FlMTYwZWM0MDM5ODZmMmY1YTYwNmNjYmI4NTM1Nzk1N2MwMWZhOWUyMiJ9; expires=Sat, 19-Nov-2022 20:01:48 GMT; Max-Age=2592000; path=/; secure; httponly
D/OkHttp  (22948): <!DOCTYPE html>
D/OkHttp  (22948): <html lang="en" class="auth-html">
D/OkHttp  (22948): 
D/OkHttp  (22948): <head>
D/OkHttp  (22948):     <meta charset="utf-8"/>
D/OkHttp  (22948):     <title>Desk360</title>
D/OkHttp  (22948):     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
D/OkHttp  (22948):     <meta name="csrf-token" content="dn0hw2HKrKLSZucb6aPZaTi8rXZDnbEedcyntLpV">
D/OkHttp  (22948):     <meta name="robots" content="noindex, nofollow">
D/OkHttp  (22948):     <link rel="shortcut icon" href="assets/images/favicon/favicon.ico">
D/OkHttp  (22948):     <link href="/assets/css/icons.min.css?v=1.2" rel="stylesheet" type="text/css"/>
D/OkHttp  (22948):     <link href="/assets/css/app.min.css?v=1.2" rel="stylesheet" type="text/css"/>
D/OkHttp  (22948):     
D/OkHttp  (22948):     <script>
D/OkHttp  (22948):     !function(f,b,e,v,n,t,s)
D/OkHttp  (22948):     {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
D/OkHttp  (22948):     n.callMethod.apply(n,arguments):n.queue.push(arguments)};
D/OkHttp  (22948):     if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
D/OkHttp  (22948):     n.queue=[];t=b.createElement(e);t.async=!0;
D/OkHttp  (22948):     t.src=v;s=b.getElementsByTagName(e)[0];
D/OkHttp  (22948):     s.parentNode.insertBefore(t,s)}(window, document,'script',
D/OkHttp  (22948):     'https://connect.facebook.net/en_US/fbevents.js');
D/OkHttp  (22948):     fbq('init', '2426694090883280');
D/OkHttp  (22948):     fbq('track', 'PageView');
D/OkHttp  (22948):     </script>
D/OkHttp  (22948):     <noscript><img height="1" width="1" style="display:none"
D/OkHttp  (22948):     src="https://www.facebook.com/tr?id=2426694090883280&ev=PageView&noscript=1"
D/OkHttp  (22948):     /></noscript>
D/OkHttp  (22948):     
D/OkHttp  (22948): </head>
D/OkHttp  (22948): 
D/OkHttp  (22948): <body class="auth-body-bg">
D/OkHttp  (22948): 
D/OkHttp  (22948):     <div class="auth-header">
D/OkHttp  (22948):         <div class="container">
D/OkHttp  (22948):         <a href="https://teknasyon.desk360.com/login" class="auth-logo">
D/OkHttp  (22948):             <span>
D/OkHttp  (22948):                 <img src="/assets/images/logo-d.png" alt="" height="20">
D/OkHttp  (22948):                 
D/OkHttp  (22948):             </span>
D/OkHttp  (22948):         </a>
D/OkHttp  (22948):         </div>
D/OkHttp  (22948):     </div>
D/OkHttp  (22948): 
D/OkHttp  (22948):     <div class="auth-content">
D/OkHttp  (22948):         <div class="container-fluid">
D/OkHttp  (22948): 
D/OkHttp  (22948):             
D/OkHttp  (22948):             <section class="form-page">
D/OkHttp  (22948): 
D/OkHttp  (22948):                 
D/OkHttp  (22948): <h1 class="fp-title">Sign in to your <span class="text-capitalize">teknasyon</span></h1>
D/OkHttp  (22948): <h2 class="fp-subtitle">teknasyon.desk360.com</h2>
D/OkHttp  (22948): 
D/OkHttp  (22948): 
D/OkHttp  (22948): <div class="auth-login">
D/OkHttp  (22948): 
D/OkHttp  (22948):     
D/OkHttp  (22948):         
D/OkHttp  (22948): 
D/OkHttp  (22948):     <div class="auth-form">
D/OkHttp  (22948): 
D/OkHttp  (22948):         <div class="form-row-or">
D/OkHttp  (22948):             <p>Enter your e-mail address and password</p>
D/OkHttp  (22948):         </div>
D/OkHttp  (22948): 
D/OkHttp  (22948):         
D/OkHttp  (22948):         <form class="needs-validation" method="POST" action="https://teknasyon.desk360.com/login"  novalidate>
D/OkHttp  (22948):             <input type="hidden" name="_token" value="dn0hw2HKrKLSZucb6aPZaTi8rXZDnbEedcyntLpV">
D/OkHttp  (22948):             <div class="form-group">
D/OkHttp  (22948):                 <input id="email" class="form-control" type="email" name="email"
D/OkHttp  (22948):                     spellcheck="false" data-rule-email="true"
D/OkHttp  (22948):                     data-rule-required="true" data-msg-required=""
D/OkHttp  (22948):                     data-msg-email="" required  placeholder="name@example.com">
D/OkHttp  (22948):                 <input type="hidden" value="" id="timezone" name="timezone">
D/OkHttp  (22948):             </div>
D/OkHttp  (22948):             <div class="form-group">
D/OkHttp  (22948):                 <input id="password" class="form-control" type="password" name="password"
D/OkHttp  (22948):                     data-msg-required="" data-rule-required="true" autocomplete="off" required placeholder="Password">
D/OkHttp  (22948):             </div>
D/OkHttp  (22948):             <div class="form-group form-group-action text-center">
D/OkHttp  (22948):                 <button class="auth-button button-gradient-green full-width">Sign In</button>
D/OkHttp  (22948):             </div>
D/OkHttp  (22948):             <div class="form-group mt-3">
D/OkHttp  (22948):                 <div class="row">
D/OkHttp  (22948):                     <div class="col-md-5 col-lg-5">
D/OkHttp  (22948):                         <div class="custom-control custom-checkbox forgot-password ml-0">
D/OkHttp  (22948):                             <input type="checkbox" class="custom-control-input" id="checkbox-signin">
D/OkHttp  (22948):                             <label class="custom-control-label" for="checkbox-signin">Remember me</label>
D/OkHttp  (22948):                         </div>
D/OkHttp  (22948):                     </div>
D/OkHttp  (22948):                     <div class="col-md-7 col-lg-7 text-md-right mt-2 mt-md-0">
D/OkHttp  (22948):                         <a href="https://teknasyon.desk360.com/password/reset" class="auth-link">
D/OkHttp  (22948):                             Forgot your password?
D/OkHttp  (22948):                         </a>
D/OkHttp  (22948):                     </div>
D/OkHttp  (22948):                 </div>
D/OkHttp  (22948):             </div>
D/OkHttp  (22948):         </form>
D/OkHttp  (22948):         
D/OkHttp  (22948): 
D/OkHttp  (22948):     </div>
D/OkHttp  (22948):     
D/OkHttp  (22948):     <script type="application/javascript">
D/OkHttp  (22948):         let d = new Date();
D/OkHttp  (22948):         let offset = d.getTimezoneOffset();
D/OkHttp  (22948):         document.getElementById("timezone").value = offset;
D/OkHttp  (22948):     </script>
D/OkHttp  (22948): 
D/OkHttp  (22948): </div>
D/OkHttp  (22948): 
D/OkHttp  (22948): 
D/OkHttp  (22948): 
D/OkHttp  (22948):             </section>
D/OkHttp  (22948):             
D/OkHttp  (22948): 
D/OkHttp  (22948):         </div>
D/OkHttp  (22948):     </div>
D/OkHttp  (22948): 
D/OkHttp  (22948):     
D/OkHttp  (22948):     <script type="text/javascript" src="/assets/js/app.min.js?v=1.2"></script>
D/OkHttp  (22948): 
D/OkHttp  (22948): </body>
D/OkHttp  (22948): </html>
D/OkHttp  (22948): <-- END HTTP (4588-byte body)
E/desk360-Failure(22948): Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
W/ActivityThread(22948): handleWindowVisibility: no activity for token android.os.BinderProxy@5726f97
W/com.gomeat.app(22948): Accessing hidden method Landroid/content/ContextWrapper;->getDisplay()Landroid/view/Display; (greylist, linking, allowed)
D/OkHttp  (22948): --> POST https://teknasyon.desk360.com/api/v1/sdk/configurations
D/OkHttp  (22948): Content-Type: application/json; charset=UTF-8
D/OkHttp  (22948): Content-Length: 42
D/OkHttp  (22948): Authorization: Bearer HoV8gyw2KIGtTcrSqX0S7xjyHcUEN3uJhboYLUHwxcVZzVP9tCohHkMg3iyIMj7Q8vxQOJjMMIaT6owR
D/OkHttp  (22948): {"country_code":"PK","language_code":"en"}
D/OkHttp  (22948): --> END POST (42-byte body)
D/OkHttp  (22948): --> POST https://teknasyon.desk360.com/api/v1/devices/register
D/OkHttp  (22948): Content-Type: application/json; charset=UTF-8
D/OkHttp  (22948): Content-Length: 171
D/OkHttp  (22948): {"app_key":"DHTyOlPu4WFVqJmlLxKPbTe82Z5hwWxD","app_platform":"Android","app_version":"1.0.0","device_id":"QKQ1.200209.002","language_code":"en","time_zone":"Asia/Karachi"}
D/OkHttp  (22948): --> END POST (171-byte body)
D/ColorViewRootUtil(22948): initSwipState, isDisplayCompatApp false
D/ColorViewRootUtil(22948): mScreenHeight 1600, mScreenWidth 720
D/WindowManager(22948): Add to mViews: DecorView@4a246be[Desk360BaseActivity], this = android.view.WindowManagerGlobal@876ab23,pkg= com.gomeat.app
I/Choreographer(22948): Skipped 14 frames!  The application may be doing too much work on its main thread.
D/OkHttp  (22948): <-- 200 OK https://teknasyon.desk360.com/login (398ms)
D/OkHttp  (22948): Date: Thu, 20 Oct 2022 20:01:49 GMT
D/OkHttp  (22948): Content-Type: text/html; charset=UTF-8
D/OkHttp  (22948): Transfer-Encoding: chunked
D/OkHttp  (22948): Connection: keep-alive
D/OkHttp  (22948): Server: nginx/1.20.0
D/OkHttp  (22948): Cache-Control: no-cache, private
D/OkHttp  (22948): X-Frame-Options: SAMEORIGIN
D/OkHttp  (22948): Set-Cookie: XSRF-TOKEN=eyJpdiI6Imhoa3NXRjMyMFhrNnA1bE5iVDRzUnc9PSIsInZhbHVlIjoiSjBxQWRCaXJuK0FLNnNXU09FZFJuMkorQUVoV0xHOENIdkFGcFQ2WTJac2pOUkZOaVhaOGtBdnA4TW5maGg4VyIsIm1hYyI6ImNiZDE4MWEwODFkZDA1ZjQ2YWZhZjc1MGZiZjY4OGIwODc5ZmFlZTNmMzZlNjk1Zjk0NGQ0YTA2NThjYzFmOWQifQ%3D%3D; expires=Sat, 19-Nov-2022 20:01:49 GMT; Max-Age=2592000; path=/; secure
D/OkHttp  (22948): Set-Cookie: desk360_session=eyJpdiI6IkJKRGxmNFVEUWV0d29lRDYza1R4TFE9PSIsInZhbHVlIjoibHowZWd6c1lDdlU0bHRVb0tON3JkenVLZGFuckVtMHN0ZjJGam5pXC9rdGZYQ1VmSnU4R3VNcWgydk1PVTZHSWUiLCJtYWMiOiIwNGU3MGVlOGQ5NmM5ZTQ0ZjQ3OTU1NmZiYWE4N2NlMmNjZTJlNzY2ZDg5YTZmZmM4OTdiM2Y3N2JkZTU0Nzk0In0%3D; expires=Sat, 19-Nov-2022 20:01:49 GMT; Max-Age=2592000; path=/; secure; httponly
D/OkHttp  (22948): <!DOCTYPE html>
D/OkHttp  (22948): <html lang="en" class="auth-html">
D/OkHttp  (22948): 
D/OkHttp  (22948): <head>
D/OkHttp  (22948):     <meta charset="utf-8"/>
D/OkHttp  (22948):     <title>Desk360</title>
D/OkHttp  (22948):     <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
D/OkHttp  (22948):     <meta name="csrf-token" content="zbf127GyWlesjc3c1g6gG9DUHfxlbzuh7bv8TLM7">
D/OkHttp  (22948):     <meta name="robots" content="noindex, nofollow">
D/OkHttp  (22948):     <link rel="shortcut icon" href="assets/images/favicon/favicon.ico">
D/OkHttp  (22948):     <link href="/assets/css/icons.min.css?v=1.2" rel="stylesheet" type="text/css"/>
D/OkHttp  (22948):     <link href="/assets/css/app.min.css?v=1.2" rel="stylesheet" type="text/css"/>
D/OkHttp  (22948):     
D/OkHttp  (22948):     <script>
D/OkHttp  (22948):     !function(f,b,e,v,n,t,s)
D/OkHttp  (22948):     {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
D/OkHttp  (22948):     n.callMethod.apply(n,arguments):n.queue.push(arguments)};
D/OkHttp  (22948):     if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
D/OkHttp  (22948):     n.queue=[];t=b.createElement(e);t.async=!0;
D/OkHttp  (22948):     t.src=v;s=b.getElementsByTagName(e)[0];
D/OkHttp  (22948):     s.parentNode.insertBefore(t,s)}(window, document,'script',
D/OkHttp  (22948):     'https://connect.facebook.net/en_US/fbevents.js');
D/OkHttp  (22948):     fbq('init', '2426694090883280');
D/OkHttp  (22948):     fbq('track', 'PageView');
D/OkHttp  (22948):     </script>
D/OkHttp  (22948):     <noscript><img height="1" width="1" style="display:none"
D/OkHttp  (22948):     src="https://www.facebook.com/tr?id=2426694090883280&ev=PageView&noscript=1"
D/OkHttp  (22948):     /></noscript>
D/OkHttp  (22948):     
D/OkHttp  (22948): </head>
D/OkHttp  (22948): 
D/OkHttp  (22948): <body class="auth-body-bg">
D/OkHttp  (22948): 
D/OkHttp  (22948):     <div class="auth-header">
D/OkHttp  (22948):         <div class="container">
D/OkHttp  (22948):         <a href="https://teknasyon.desk360.com/login" class="auth-logo">
D/OkHttp  (22948):             <span>
D/OkHttp  (22948):                 <img src="/assets/images/logo-d.png" alt="" height="20">
D/OkHttp  (22948):                 
D/OkHttp  (22948):             </span>
D/OkHttp  (22948):         </a>
D/OkHttp  (22948):         </div>
D/OkHttp  (22948):     </div>
D/OkHttp  (22948): 
D/OkHttp  (22948):     <div class="auth-content">
D/OkHttp  (22948):         <div class="container-fluid">
D/OkHttp  (22948): 
D/OkHttp  (22948):             
D/OkHttp  (22948):             <section class="form-page">
D/OkHttp  (22948): 
D/OkHttp  (22948):                 
D/OkHttp  (22948): <h1 class="fp-title">Sign in to your <span class="text-capitalize">teknasyon</span></h1>
D/OkHttp  (22948): <h2 class="fp-subtitle">teknasyon.desk360.com</h2>
D/OkHttp  (22948): 
D/OkHttp  (22948): 
D/OkHttp  (22948): <div class="auth-login">
D/OkHttp  (22948): 
D/OkHttp  (22948):     
D/OkHttp  (22948):         
D/OkHttp  (22948): 
D/OkHttp  (22948):     <div class="auth-form">
D/OkHttp  (22948): 
D/OkHttp  (22948):         <div class="form-row-or">
D/OkHttp  (22948):             <p>Enter your e-mail address and password</p>
D/OkHttp  (22948):         </div>
D/OkHttp  (22948): 
D/OkHttp  (22948):         
D/OkHttp  (22948):         <form class="needs-validation" method="POST" action="https://teknasyon.desk360.com/login"  novalidate>
D/OkHttp  (22948):             <input type="hidden" name="_token" value="zbf127GyWlesjc3c1g6gG9DUHfxlbzuh7bv8TLM7">
D/OkHttp  (22948):             <div class="form-group">
D/OkHttp  (22948):                 <input id="email" class="form-control" type="email" name="email"
D/OkHttp  (22948):                     spellcheck="false" data-rule-email="true"
D/OkHttp  (22948):                     data-rule-required="true" data-msg-required=""
D/OkHttp  (22948):                     data-msg-email="" required  placeholder="name@example.com">
D/OkHttp  (22948):                 <input type="hidden" value="" id="timezone" name="timezone">
D/OkHttp  (22948):             </div>
D/OkHttp  (22948):             <div class="form-group">
D/OkHttp  (22948):                 <input id="password" class="form-control" type="password" name="password"
D/OkHttp  (22948):                     data-msg-required="" data-rule-required="true" autocomplete="off" required placeholder="Password">
D/OkHttp  (22948):             </div>
D/OkHttp  (22948):             <div class="form-group form-group-action text-center">
D/OkHttp  (22948):                 <button class="auth-button button-gradient-green full-width">Sign In</button>
D/OkHttp  (22948):             </div>
D/OkHttp  (22948):             <div class="form-group mt-3">
D/OkHttp  (22948):                 <div class="row">
D/OkHttp  (22948):                     <div class="col-md-5 col-lg-5">
D/OkHttp  (22948):                         <div class="custom-control custom-checkbox forgot-password ml-0">
D/OkHttp  (22948):                             <input type="checkbox" class="custom-control-input" id="checkbox-signin">
D/OkHttp  (22948):                             <label class="custom-control-label" for="checkbox-signin">Remember me</label>
D/OkHttp  (22948):                         </div>
D/OkHttp  (22948):                     </div>
D/OkHttp  (22948):                     <div class="col-md-7 col-lg-7 text-md-right mt-2 mt-md-0">
D/OkHttp  (22948):                         <a href="https://teknasyon.desk360.com/password/reset" class="auth-link">
D/OkHttp  (22948):                             Forgot your password?
D/OkHttp  (22948):                         </a>
D/OkHttp  (22948):                     </div>
D/OkHttp  (22948):                 </div>
D/OkHttp  (22948):             </div>
D/OkHttp  (22948):         </form>
D/OkHttp  (22948):         
D/OkHttp  (22948): 
D/OkHttp  (22948):     </div>
D/OkHttp  (22948):     
D/OkHttp  (22948):     <script type="application/javascript">
D/OkHttp  (22948):         let d = new Date();
D/OkHttp  (22948):         let offset = d.getTimezoneOffset();
D/OkHttp  (22948):         document.getElementById("timezone").value = offset;
D/OkHttp  (22948):     </script>
D/OkHttp  (22948): 
D/OkHttp  (22948): </div>
D/OkHttp  (22948): 
D/OkHttp  (22948): 
D/OkHttp  (22948): 
D/OkHttp  (22948):             </section>
D/OkHttp  (22948):             
D/OkHttp  (22948): 
D/OkHttp  (22948):         </div>
D/OkHttp  (22948):     </div>
D/OkHttp  (22948): 
D/OkHttp  (22948):     
D/OkHttp  (22948):     <script type="text/javascript" src="/assets/js/app.min.js?v=1.2"></script>
D/OkHttp  (22948): 
D/OkHttp  (22948): </body>
D/OkHttp  (22948): </html>
D/OkHttp  (22948): <-- END HTTP (4588-byte body)
D/AndroidRuntime(22948): Shutting down VM
E/AndroidRuntime(22948): FATAL EXCEPTION: main
E/AndroidRuntime(22948): Process: com.gomeat.app, PID: 22948
E/AndroidRuntime(22948): android.view.InflateException: Couldn't resolve menu item onClick handler goBackButtonClicked in class com.teknasyon.desk360.view.activity.Desk360BaseActivity
E/AndroidRuntime(22948): 	at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.<init>(SupportMenuInflater.java:255)
E/AndroidRuntime(22948): 	at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:484)
E/AndroidRuntime(22948): 	at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:531)
E/AndroidRuntime(22948): 	at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:207)
E/AndroidRuntime(22948): 	at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:129)
E/AndroidRuntime(22948): 	at com.teknasyon.desk360.view.activity.Desk360BaseActivity.onCreateOptionsMenu(Desk360BaseActivity.kt:193)
E/AndroidRuntime(22948): 	at android.app.Activity.onCreatePanelMenu(Activity.java:4202)
E/AndroidRuntime(22948): 	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
E/AndroidRuntime(22948): 	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
E/AndroidRuntime(22948): 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3106)
E/AndroidRuntime(22948): 	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:458)
E/AndroidRuntime(22948): 	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:58)
E/AndroidRuntime(22948): 	at android.os.Handler.handleCallback(Handler.java:899)
E/AndroidRuntime(22948): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(22948): 	at android.os.Looper.loop(Looper.java:238)
E/AndroidRuntime(22948): 	at android.app.ActivityThread.main(ActivityThread.java:7853)
E/AndroidRuntime(22948): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22948): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(22948): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)
E/AndroidRuntime(22948): Caused by: java.lang.NoSuchMethodException: com.teknasyon.desk360.view.activity.Desk360BaseActivity.goBackButtonClicked [interface android.view.MenuItem]
E/AndroidRuntime(22948): 	at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(22948): 	at java.lang.Class.getMethod(Class.java:1693)
E/AndroidRuntime(22948): 	at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.<init>(SupportMenuInflater.java:251)
E/AndroidRuntime(22948): 	... 18 more
I/Process (22948): Sending signal. PID: 22948 SIG: 9
Lost connection to device.

**Comment by jirorenc** [comment]
I have same problem to @widget-404.

**Comment by jirorenc** [comment]
> 
hello, Did you find any solve for this problem?

**Comment by widget-404** [comment]
@jirorenc no, I didn't find any solution for this. I contacted their customer support and they said there is no issue on their side, so I used another package for my requirements.

**Comment by jirorenc** [comment]
> @jirorenc no, I didn't find any solution for this. I contacted their customer support and they said there is no issue on their side, so I used another package for my requirements.

I see, well Which package did you use?

**Comment by widget-404** [comment]
> > @jirorenc no, I didn't find any solution for this. I contacted their customer support and they said there is no issue on their side, so I used another package for my requirements.
> 
> I see, well Which package did you use?

@jirorenc actually it's not a package for flutter, I'm using `https://www.tawk.to`. I just set up an account and open their link on InAppWebView from my app. and it's working perfectly.

**Comment by jirorenc** [comment]
I see, thanks so mach. by the way, this issue is that originated to clash desk360 with flutter_inappwebview package.

**Comment by jirorenc** [comment]
> > > @jirorenc no, I didn't find any solution for this. I contacted their customer support and they said there is no issue on their side, so I used another package for my requirements.
> > 
> > 
> > I see, well Which package did you use?
> 
> @jirorenc actually it's not a package for flutter, I'm using `https://www.tawk.to`. I just set up an account and open their link on InAppWebView from my app. and it's working perfectly.

I see, thanks so mach. by the way, this issue is that originated to clash desk360 with flutter_inappwebview package.

**Comment by DineshIT** [comment]
Hi Dudes, 

I'm also facing this issue of crashing while loading the support page in Flutter [ANdroid 13]
